name: pack-man-example
version: 18.9.2+204
description: Pack-Man example pubspec.yaml
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.3.0
  auto_size_text: null
  avatar_glow: ^3.0.1
  awesome_notifications: ^0.10.1
  back_button_interceptor: ^8.0.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  concentric_transition: null
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dio: null
  draggable_home: null
  expandable_text: ^2.3.0
  extended_masked_text: ^3.0.1
  facebook_app_events: ^0.21.0
  firebase_analytics: ^12.0.4
  firebase_app_check: ^0.4.1+2
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_database: ^12.1.0
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_carousel_widget: ^3.1.0
  flutter_floating_bottom_bar: ^1.3.0
  flutter_form_builder: ^10.2.0
  flutter_gen: ^5.12.0
  flutter_inappwebview: ^6.1.5
  flutter_inappwebview_android: ^1.1.3
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: null
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.3
  future_debounce_button: ^0.3.0
  get: ^5.0.0-release-candidate-9.3.2
  google_fonts: null
  google_generative_ai: ^0.4.7
  google_mobile_ads: ^6.0.0
  google_sign_in: ^7.2.0
  google_sign_in_android: ^7.2.6
  gpt_markdown: ^1.1.4
  http: ^1.6.0
  icons_plus: ^5.0.0
  in_app_purchase: ^3.2.3
  in_app_review: ^2.0.11
  in_app_update: ^4.2.5
  liquid_pull_to_refresh: ^3.0.1
  loading_animation_widget: ^1.3.0
  logger: null
  lottie: null
  markdown: ^7.3.0
  onesignal_flutter: ^5.3.4
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  qr_flutter: ^4.1.0
  searchable_listview: ^2.19.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.17
  shimmer: null
  step_progress_indicator: ^1.0.2
  storyly_flutter: ^4.16.3
  upgrader: ^12.3.0
  url_launcher: null
  url_launcher_android: ^6.3.28
  version: ^3.0.2
  webview_flutter_android: ^4.10.9
  whatsapp_unilink: ^2.1.0
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  build_runner: null
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: null
  flutter_lints: null
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "FCFCFF"
  color_dark: "1A1C1E"
  image: assets/images/logo_short.png
  image_dark: assets/images/logo_short_dark.png
  android_gravity: center
  android: true
  web: false
  ios: false

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/app_icon.png"
  adaptive_icon_background: "assets/app/app_icon_adaptive_back.png"
  adaptive_icon_foreground: "assets/app/app_icon_adaptive_fore.png"

flutter:
  uses-material-design: true
